### PR TITLE
TRT questionnaire - fix question header text

### PR DESCRIPTION
**Pull request by achen2401**
Update question header texts per [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1726780943824539?thread_ts=1726527783.833589&cid=C01P9V67NMA)
reduced text (see screen shot after changes):

Screenshot 2024-09-19 at 2 45 10 PM

### CODE REVIEW

**Comment by achen2401** [comment]
@mcjustin in case you miss this.. this is ready for you to review.  There are more requested text changes for the PainTracker TRT questionnaire.

**Review by mcjustin — COMMENTED** [review]
We need to figure out how to better model this in FHIR, namely, how to capture both 1) the text of the item as displayed to the person responding to the questionnaire, and 2) the text that we want to display for clinician interpretation. 

Questionnaire.item.text doesn't seem to say anything about supporting this
https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.text

Haven't we done this before @achen2401 ?

**Comment by achen2401** [comment]
> We need to figure out how to better model this in FHIR, namely, how to capture both 1) the text of the item as displayed to the person responding to the questionnaire, and 2) the text that we want to display for clinician interpretation.
> 
> Questionnaire.item.text doesn't seem to say anything about supporting this https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.text
> 
> Haven't we done this before @achen2401 ?

@mcjustin I don't recall.  At least I don't recall us having done it on the questionnaire JSON level

**Review by mcjustin — APPROVED** [review]

**Comment by achen2401** [comment]
@mcjustin sorry for all the edits, but I did just do another update(`PUT`) on the Paintracker TRT questionnaire in the shared dev instance (see [here](https://dashboard.acc.dev.cosri.cirg.washington.edu/))  You will need to do the same for the staging and production instances again when you have a moment.

**Pull request merged**
